Blog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
	title = StringField('Title',validators=[DataRequired()])
	text = StringField('Text',validators=[DataRequired()])
	submit = SubmitField('Post')

Blog/blog_posts/views.py
from flask import render_template,url_for,flash,request,redirect,Blueprint
from flask_login import current_user,login_required
from flask import abort
from Blog.models import BlogPost, User
from Blog.blog_posts.forms import BlogPostForm
from Blog import blog_posts, db

blog_posts = Blueprint('blog_posts',__name__)
#Creating a blogpost
#Viewing a blogpost
#Updating a blogpost
#Deleting a blogpost

@blog_posts.route('/create',methods = ['GET','POST'])
@login_required
def create_post():
	form = BlogPostForm()
	if form.validate_on_submit():
		blog_post = BlogPost(title = form.title.data,text = form.text.data,user_id=current_user.id)

		db.session.add(blog_post)
		db.session.commit()
		flash('Blog Post Created')

		return redirect(url_for('core.feed'))
	return render_template('create_post.html',form = form)

@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):

	blog_post = BlogPost.query.get_or_404(blog_post_id)
	print(f"One blog post is {blog_post}")
	author = User.query.get(blog_post.user_id)
	access = False
	if author.username == current_user.username:
		access = True
	else:
		access = False
	print(f"Cureent user is {current_user.username}")
	print(f"pOST's author is {author.username}")
	return render_template('blog_post.html',title = blog_post.title,date = blog_post.date,post = blog_post,author = author,access = access)

@blog_posts.route('/<int:blog_post_id>/update',methods = ['GET','POST'])
@login_required
def update(blog_post_id):
	blog_post = BlogPost.query.get_or_404(blog_post_id)
	author = User.query.get(blog_post.user_id)
	print(f"Updating section, author name : {author.username}, current_user_name : {current_user.username}")
	if author.username != current_user.username:
		abort(403)

	form = BlogPostForm()
	if form.validate_on_submit():
		blog_post.title = form.title.data
		blog_post.text = form.text.data
		db.session.commit()
		flash('Form Updated')
		return redirect(url_for('blog_posts.blog_post',blog_post_id = blog_post_id))

	elif request.method == 'GET':
		form.title.data = blog_post.title
		form.text.data = blog_post.text

	return render_template('create_post.html',title = 'Updating',form = form)


@blog_posts.route('/<int:blog_post_id>/delete',methods = ['GET','POST'])
@login_required
def delete_post(blog_post_title):
	
	blog_post = BlogPost.query.filter_by(title = blog_post_title).first()
	author = User.query.get(blog_post.user_id)
	print(f"Deleting section, author name : {author.username}, current_user_name : {current_user.username}")
	if author.username != current_user.username:
		abort(403)
	db.session.delete(blog_post)
	db.session.commit()
	flash('bLOG  poST Deleted')
	return redirect(url_for('core.feed'))

Blog/core/views.py
# core/views.py
from Blog.blog_posts.views import blog_post
from flask import render_template,request,Blueprint
from Blog.models import BlogPost

core = Blueprint('core',__name__)
@core.route('/')
def index():

	return render_template('index.html')

@core.route('/info')
def info():
	return render_template('info.html')

@core.route('/feed')
def feed():
	page = request.args.get('page',1,type=int)
	blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page = page,per_page = 5)
	print(f"BLOG POST ARE --------------------------------------- {blog_posts}")
	return render_template('feed.html',blog_posts = blog_posts)

Blog/health/views.py
from flask import render_template,url_for,flash,Blueprint,request
import csv

health = Blueprint('health',__name__)

@health.route('/health_page')
def health_page():
	return render_template('health.html')

@health.route('/mental_health',methods = ['GET','POST'])
def mental_health():
	mental_health_status = request.form.get("mentalHealthStaus", False)
	print(f"Mental health status is {mental_health_status}")
	return render_template('mental_health.html')

@health.route('/menstrual_health',methods = ['GET','POST'])
def menstrual_health():
	return render_template('menstrual_health.html')

@health.route('/period_tracker',methods = ['GET','POST'])
def period_tracker():
	print('tracking periods')
	return render_template('/period-tracker/period_tracker.html')

Blog/users/views.py
from flask import render_template,url_for,flash,Blueprint,request
from flask_login import login_user,logout_user,current_user,login_required
from werkzeug.utils import redirect
from Blog import db
from Blog.models import User,BlogPost
from Blog.users.forms import LoginForm,RegistrationForm,UpdateUserForm
from Blog.users.picture_handler import add_profile

users = Blueprint('users',__name__)

@users.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('core.index'))

@users.route('/register',methods = ['GET','POST'])
def register():
	form = RegistrationForm()
	if form.validate_on_submit():
		user = User(email = form.email.data,username=form.username.data,password=form.password.data)
		db.session.add(user)
		db.session.commit()
		flash("Thanks for registration")
		return redirect(url_for('users.login'))

	return render_template('register.html',form = form)


@users.route('/login',methods = ['GET','POST'])
def login():
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email = form.email.data).first()

		if user.check_password(form.password.data) and user is not None:
			login_user(user)
			flash('Log In Success')

			next = request.args.get('next')

			if next == None or not next[0] == '/0':
				next = url_for('core.index')
			return redirect(next)

	return render_template('login.html',form = form)

@users.route('/account',methods = ['GET','POST'])
@login_required
def account():

	form = UpdateUserForm()
	if form.validate_on_submit():

		if form.picture.data:
			username= current_user.username
			pic = add_profile(form.picture.data,username)
			current_user.profile_image = pic

		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('User account updated')
		return redirect(url_for('users.account'))

	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email

	profile_image = url_for('static',filename = 'profile_pics/' + current_user.profile_image)
	print(f"Path to the profile image : {profile_image} ")
	return render_template('account.html',profile_image = profile_image,form= form)

@users.route('/<username>')
def user_posts(username):
	page = request.args.get('page',1,type = int)
	#Get the user or go to error page
	user = User.query.filter_by(username = username).first_or_404()
	blog_posts = BlogPost.query.filter_by(author = user).order_by(BlogPost.date.desc()).paginate(page=page,per_page = 5)
	return render_template('user_blog_posts.html',blog_posts = blog_posts,user = user)

Blog/templates/account.html
{% extends 'base.html' %}
{% block content %}
<div align='center'>
	<!-- <h1>Welcome, {{current_user.username}}</h1> -->
	<div class="outer-account-container">
		<div class="profile-card-container">
			<img src="/static/default-profile.png" alt="" class="profile-picture">
			<div class="profile-text-container">
				<h4>Email : {{current_user.email}}</h4>
				<h4>Username : {{current_user.username}}</h4>
				<h4>Blood type : A+ve</h4>
				<h4>Allergy to a drug : None</h4>

			</div>
		</div>
		<div class="qrcode">
			<img src="/static/qrcode.jpg" alt="">
		</div>
	</div>

</div>

{% endblock %}

Blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% block head %}

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
		integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
		integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
		integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
		crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
		integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
		crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
		integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
		integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
		crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
		integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
		crossorigin="anonymous"></script>


	<link rel="stylesheet" href="{{url_for('static',filename = 'styles.css')}}">
</head>

{% endblock %}

<body>
	<main>
		{% block navbar %}
		<nav class="navbar navbar-expand-lg navbar-light ">
			<div class="container-fluid">
				<a href="{{url_for('core.index')}}"><img class='navbar-brand' src="/static/syringe_logo.png" alt=""
						height="40"></a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
					aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav">

						<!-- <li class="nav-link"><a href="{{url_for('core.info')}}">Info</a></li> -->
						{% if current_user.is_authenticated %}
						<li class="nav-link"><a href="{{url_for('core.feed')}}">Forum</a></li>
						<li class="nav-link"><a href="{{url_for('health.health_page')}}">Health</a></li>
						<li class="nav-link"><a href="{{url_for('blog_posts.create_post')}}">Create Posts</a></li>
						<li class="nav-link"><a href="{{url_for('users.account')}}">Account</a></li>
						<li class="nav-link"><a href="{{url_for('users.logout')}}">Log Out</a></li>



						{% else %}
						<li class="nav-link"><a href="{{url_for('users.register')}}">Register</a></li>
						<li class="nav-link"><a href="{{url_for('users.login')}}">Log In</a></li>
						{% endif %}

					</ul>
				</div>
			</div>
		</nav>


		{% endblock %}
		{% block content %}
		{% endblock %}

	</main>


</body>

</html>

Blog/templates/blog_post.html
{% extends 'base.html' %}
{% block content %}

<h1>{{title}}</h1>
<h2>Written by: {{author.username}}</h2>
<h3>Published: {{date.strftime('%B %d %Y')}}</h3>
<p>{{post.text}}</p>

{% if access %}
<div>
	<a href="{{url_for('blog_posts.update',blog_post_id = post.id)}}">Update</a>
	<button class="btn btn-danger" data-toggle='modal' data-target='#del_modal'>Delete</button>
	<div class="modal" tabindex="-1" id='del_modal'>
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">Delete Post ?</h5>
					<button type="buttons" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<p>Post will be permenantly deleted.Click delete if you want to continue.</p>
				</div>
				<div class="modal-footer">
					<form action="{{url_for('core.index')}}" method='POST'>
						<input type="submit" value="Cancel" class="btn btn-secondary">
					</form>
					<form action="{{url_for('blog_posts.delete_post',blog_post_title = title,blog_post_id = post.id)}}"
						method='POST'>
						<input type="submit" value="Delete" class="btn btn-danger">
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endif %}

{% endblock %}

Blog/templates/blog_posts.html
{% block extends 'base.html'%}
{% block content %}
<div class="jumbotron">
	<h1>{{post.title}}</h1>
	<h2>Written by : {{post.author.username}}</h2>
	<h3>Published by : {{post.date.strftime(" %B %d %Y")}}</h3>
	<p>{{post.text}}</p>
	{% if post.author == current_user %}
	<div>
		<a href="{{url_for('blog_posts.update',blog_post_id = post_id)}}">Update</a>
		<button type='button' class='btn btn-danger' name='button' data-toggle='modal'
			data-target='#del-modal'>Delete</button>
	</div>


	{% endif %}
</div>

<div class="modal" tabindex="-1" id='del-modal'>
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Delete</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to delete?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
				<form action="{{url_for('blog_posts.delete_post',blog_post_id = post_id)}}" method="POST">
					<input type="submit" value='Delete' class="btn btn-danger">
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock %}

Blog/templates/create_post.html
{% extends 'base.html'%}
{% block content %}
<div class="container create-post-container">
	<form class='form-group' method="POST">
		{{form.hidden_tag()}}

		<div class="form-group">
			<div class="label">{{form.title.label(class = 'form-control-label')}}</div>
			{{form.title(class = 'form-control form-control-lg')}}

		</div>
		<div class="form-group">

			<div class="label">{{form.text.label(class = 'form-control-label')}}</div>
			{{form.text(class = 'form-control form-control-lg')}}

		</div>
		<div class="form-group">
			{{form.submit(class = 'btn btn-outline-info')}}

		</div>
	</form>
</div>
{% endblock %}

Blog/templates/feed.html
{% extends 'base.html' %}
{% block content %}


<div class="container forum">
	{% for post in blog_posts.items %}
	<div class="card">
		<div class="card-body">
			<h2><a href="{{url_for('blog_posts.blog_post',blog_post_id = post.id)}}"
					class="card-title ">{{post.title}}</a></h2>
			<a href="{{url_for('users.user_posts',username = post.username)}}">Written By :
				{{post.username}}</a>
			<p>Published on : {{post.date.strftime('%Y-%m-%d')}}</p>
			<a href="{{url_for('blog_posts.blog_post',blog_post_id = post.id)}}" class='btn btn-primary'>Read Blog
				Post</a>
		</div>
	</div>
	{% endfor %}
</div>




<nav aria-label="Page navigation example">
	<ul class="pagination justify-content-center">
		{% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
		{% if blog_posts.page == page_num %}
		<li class="page-item disabled">
			<a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
		</li>
		</li>
		{% else %}
		<li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
		</li>
		{% endif %}
		{% endfor %}
</nav>

<style>
	main {
		overflow-y: scroll;
	}
</style>

{% endblock %}

Blog/templates/health.html
{% block head %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{{url_for('static',filename = 'stylesheet_health.css')}}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<title>Document</title>
</head>

{% endblock %}


<body>
	{% block navbar %}
	<nav>
		<a href="{{url_for('core.index')}}"> <img class='navbar-brand' src="/static/syringe_logo.png" alt=""
				height="72">
		</a>
	</nav>
	{% endblock %}
	<div class="main-container">
		<div class="container">

			<div class="content">
				<div class="text">
					{% block text_content %}
					<h1 class="heading">What do you want to check ?</h1>
					<nav class="menu">
						<a href="{{url_for('health.mental_health')}}" class="nav-item">Mental Health</a>
						<a href="#" class="nav-item">Skin Cancer</a>
						<a href="#" class="nav-item">Covid-19</a>
						<a href="{{url_for('health.menstrual_health')}}" class="nav-item">Menstrual Health</a>
						<a href="#" class="nav-item">Common Diseases</a>
					</nav>
					{% endblock %}
				</div>
			</div>

			<div class="image">
				{% block image %}
				<img src="/static/nurse_health_image.png" alt="" class="women_health_image">
				{% endblock %}
			</div>
		</div>
	</div>

</body>

</html>

Blog/templates/info.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">
	<h1>Info</h1>
	<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis in deleniti nesciunt dolores ipsum iure,
		maiores tenetur sint nobis, mollitia rerum ad ullam soluta modi impedit odio ea nihil dignissimos cupiditate
		dolor ducimus eveniet error, quisquam accusantium! Obcaecati sed temporibus eaque veniam aliquam corporis, sint
		in beatae! Mollitia dignissimos, autem sequi aperiam consequuntur odio odit totam illum libero? Dolore amet
		assumenda aliquid officia earum at quibusdam temporibus nesciunt totam, asperiores omnis odio tempore delectus
		a, odit ex sequi accusantium quam. Fuga, sed. Cupiditate delectus ullam tempore, iusto cum possimus quo, eos
		facilis expedita repellendus ducimus hic sint. Autem vel perferendis recusandae nobis. Pariatur qui perspiciatis
		consequatur tempore? Enim voluptas ullam unde nulla atque aliquam veniam quae reiciendis commodi esse? Modi
		laborum sit nisi. Ducimus nostrum temporibus sed recusandae placeat aperiam officiis labore reiciendis,
		laudantium sequi, dolore officia. Ut minima quos quaerat molestias illo qui asperiores, tenetur saepe eius nihil
		itaque atque accusamus aliquam id dignissimos maxime possimus illum veritatis sed laboriosam dicta? Ipsum sit
		facilis ab asperiores. Laboriosam officiis, quasi expedita aperiam explicabo quas repudiandae rem excepturi quod
		nobis, sit veniam enim tempore quibusdam molestias laudantium beatae dolores atque tenetur doloremque sed.
		Neque, vero ipsum? Impedit beatae dolores minus provident expedita, possimus mollitia similique. Esse explicabo
		quibusdam ut natus fuga consectetur ex iure ratione dolores quaerat aut, recusandae amet est nobis aliquid eius
		dicta minus ipsum ullam? Aut maiores harum exercitationem sapiente rem id incidunt nulla qui labore quo ducimus
		adipisci iste doloribus repellendus ad nisi, deleniti ea necessitatibus quia eveniet ipsum atque quos soluta
		commodi! Est sapiente quod dolore illo in sit exercitationem! Quibusdam, optio? Provident aliquam ratione facere
		cum temporibus aut deleniti ex modi alias. Assumenda tempora consequatur saepe deserunt sint quia, nobis cumque
		optio quis, praesentium, repellendus aspernatur voluptatem cum similique distinctio laudantium? Ratione
		inventore nemo officiis?</p>
</div>
{% endblock %}

Blog/templates/login.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
	{{form.hidden_tag()}}
	{{form.email.label}} {{form.email}} <br>
	{{form.password.label}} {{form.password}} <br>
	{{form.submit()}}
</form>
{% endblock %}

Blog/templates/menstrual_health.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;500;600;700&display=swap');

		* {
			padding: 0;
			margin: 0;
			box-sizing: border-box;
		}

		main {
			height: 100vh;
			width: 100vw;
			background-color: #fadbda;
			display: flex;
			justify-content: center;
			align-items: center;
			font-family: 'Montserrat', sans-serif;
		}

		.menstrual-container {
			width: 100%;
			height: 100%;
			display: flex;
			justify-content: center;
			align-items: center;
		}

		.menstrual-content {
			width: 45%;
			margin-right: 130px;
		}

		h3 {
			margin: 20px 0 50px 0;
			font-weight: 700;
			font-size: 1.6rem;
			text-align: justify;
		}

		h1 {
			font-size: 4.5rem;
			font-weight: 700;
		}

		p {
			text-align: justify;
			font-size: 1.2rem;
			line-height: 1.7rem;
		}

		.btn {
			margin-top: 30px;
			padding: 10px 15px;
			background-color: rgba(0, 0, 0, 0);

			outline: none;
			border: 2px solid #222;

			color: #222;
			text-transform: uppercase;
			font-weight: 600;

			transition-duration: 400ms;
		}

		.btn:hover {
			background-color: #222;
			color: #fff;
			cursor: pointer;
		}

		img {
			height: 60vh;
		}
	</style>
</head>

<body>
	<main>
		<div class="menstrual-container">
			<div class="menstrual-content">
				<h1>Healthy Periods</h1>
				<h3>Even though periods are a normal and natural part of a woman’s life, many women find that their
					periods are an intrusion or an interruption to their day-to-day life.</h3>
				<p>

					It might be that your periods just make you feel a bit run down, or tired. You may have belly aches
					and pains, nothing too serious but enough to want to spend the day on the couch with a hot water
					bottle. Serious pain and heavy bleeding should be investigated by a doctor, but low level discomfort
					can be avoided by making a number of lifestyle changes. A healthy diet, avoiding salt in your
					cooking and food, reducing caffeine intake, restoring your sleep cycle, regular daily exercise and
					reducing stress may help improve your quality of life and significantly reduce the severity of PMS
					symptoms, including reducing moodiness and painful periods. </p>

				<a href="https://naughty-hoover-ea6f99.netlify.app/"><button class="btn">Track Periods</button></a>
			</div>
			<div class="menstrual-image">
				<img src="/static/uterus.png" alt="">
			</div>
		</div>
	</main>
</body>

</html>

Blog/templates/mental_health.html
{% extends 'health.html' %}
{% block text_content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<div class="mental-health-questions">
	<div class="title">
		<h1>Mental Health Quiz</h1>
		<h4>Take your time to think but answer all the questions honestly</h4>
		<h4>There are no right or wrong answers</h4>
	</div>
	<div id="quiz"></div>
	<button id="submit">Submit</button>
	<div id="results"></div>

</div>

{% endblock %}
{% block image %}
<div class="image-container">
	<img class="mental-health-image" src="/static/mental_health.png" alt="">
</div>
<script src="{{url_for('static',filename = 'script.js')}}"></script>


{% endblock %}

Blog/templates/period_tracker.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>

<body>
	<main>
		<div class="periods-image">
			<img src="/static/period_tracker.png" alt="" width="700">
		</div>
		<div class="periods-content">
			<h1>Come let's track your periods <span>.</span></h1>
			<form action="">
				<label for="prev-date">When was your last period ?</label>
				<input type="date" name="prev-date" id="">
				<br>
				<label for="duration">For how long did it last ?</label>
				<input type="number" name="duration" id="">
				<br>
				<label for="cycle">How long is your menstrual cycle?</label>
				<input type="number">
				<br>

				<button type="submit">Check</button>
			</form>
		</div>
	</main>
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;500;600&display=swap');

		* {
			padding: 0;
			margin: 0;
			box-sizing: border-box;
		}

		main {
			height: 100vh;
			width: 100vw;
			background-color: #fadbda;
			display: flex;
			justify-content: space-evenly;
			align-items: center;
			flex-direction: column;
			font-family: 'Montserrat', sans-serif;
		}

		.periods-content {
			/* background-color: aquamarine; */
			width: 70%;
			position: relative;
			bottom: 100px;
		}

		.periods-image {
			position: relative;
			bottom: 100px;
		}

		span {
			color: #c7212d
		}
	</style>
</body>

</html>

Blog/templates/register.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
	{{form.hidden_tag()}}
	{{form.email.label}} {{form.email}} <br>
	{{form.username.label}} {{form.username}} <br>
	{{form.password.label}} {{form.password}} <br>
	{{form.pass_confirm.label}} {{form.pass_confirm}} <br>
	{{form.submit()}}
</form>
{% endblock %}

Blog/templates/user_blog_posts.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
	<div class="jumbotron">
		<h1>Welcome to the page for {{user.username}}</h1>
		<img src="{{url_for('static',filename = 'profile_pics/' + user.profile_image)}}" alt="">
	</div>
</div>

{% for blog in blog_posts.items %}
<h2>
	<a href="{{url_for('blog_post.blog_post',blog_post_id = post_id)}}">{{post.title}}</a>
</h2>
<p>Written by <a href="{{url_for('user.user_post',username = post.author.username)}}">{{post.author.username}}</a></p>
<p>Published on : {{post.date.strftime("%Y-%m-%d")}}</p>
<br>
<p>{{post.text}}</p>

{% endfor %}

<nav aria-label="Page navigation example">
	<ul class="pagination justify-content-center">

		{% for page_num in blog_posts.iter_pages(left_edge =1,right_edge = 1,left_current = 1,right_current = 1) %}
		{% if blog_posts_page == page_num %}
		<li class="page-item disabled">
			<a href="url_for{{'user.user_posts',username = user.username,page = page_num}}"
				class="page-link">{{page_num}}</a>
		</li>
		{% else %}
		<li class="page-item">
			<a href="url_for{{'user.user_posts',username = user.username,page = page_num}}"
				class="page-link">{{page_num}}</a>
		</li>
		{% endif %}
		{% endfor %}

	</ul>
</nav>
{% endblock %}